In [1]:
import tensorflow as tf

## 텐서와 그래프 실행

In [2]:
hello = tf.constant('Hello, Tensorflow')
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [3]:
aa = tf.constant([1, 2, 3])
print(aa)

Tensor("Const_1:0", shape=(3,), dtype=int32)


In [4]:
a = tf.constant(10)
b = tf.constant(32)
c = tf.add(a, b)
print(c)

Tensor("Add:0", shape=(), dtype=int32)


In [5]:
sess = tf.Session()

print(sess.run(hello))
print(sess.run([a, b, c]))

sess.close()

b'Hello, Tensorflow'
[10, 32, 42]


## 플레이스홀더와 변수

In [6]:
X = tf.placeholder(tf.float32, [None, 3])
print(X)

Tensor("Placeholder:0", shape=(?, 3), dtype=float32)


In [7]:
x_data = [[1, 2, 3], [4, 5, 6]]

In [8]:
W = tf.Variable(tf.random_normal([3, 2]))
b = tf.Variable(tf.random_normal([2, 1]))

In [9]:
expr = tf.matmul(X, W) + b

In [10]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

print("=== x_data ===")
print(x_data)
print("=== W ===")
print(sess.run(W))
print("=== b ===")
print(sess.run(b))
print("=== expr ===")
print(sess.run(expr, feed_dict={X: x_data}))

sess.close()

=== x_data ===
[[1, 2, 3], [4, 5, 6]]
=== W ===
[[-0.6388821   0.51269525]
 [ 0.31753901 -0.69192493]
 [-1.32349741  0.80374247]]
=== b ===
[[-0.89337987]
 [ 1.24560213]]
=== expr ===
[[-4.86767626  0.64669305]
 [-7.66321611  4.65921307]]


## 선형회귀모델 구현

In [11]:
x_data = [1, 2, 3]
y_data = [1, 2, 3]

In [12]:
W = tf.Variable(tf.random_uniform([1], -1.0, 1.0))
b = tf.Variable(tf.random_uniform([1], -1.0, 1.0))

In [13]:
X = tf.placeholder(tf.float32, name = "X")
Y = tf.placeholder(tf.float32, name = "Y")

In [14]:
hypothesis = W * X + b

In [15]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [16]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1)
train_op = optimizer.minimize(cost)

In [17]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(100):
        _, cost_val = sess.run([train_op, cost], feed_dict={X: x_data,
                                                        Y: y_data})
    
        print(step, cost_val, sess.run(W), sess.run(b))

0 0.866322 [ 1.31433439] [-0.61102456]
1 0.066182 [ 1.26536548] [-0.61455339]
2 0.0539721 [ 1.26351237] [-0.59778887]
3 0.0513001 [ 1.25668299] [-0.58363605]
4 0.048862 [ 1.2505666] [-0.56958205]
5 0.046541 [ 1.24453723] [-0.55589229]
6 0.0443303 [ 1.23865938] [-0.54252875]
7 0.0422246 [ 1.23292208] [-0.52948678]
8 0.0402189 [ 1.22732282] [-0.51675826]
9 0.0383084 [ 1.22185814] [-0.50433576]
10 0.0364887 [ 1.21652484] [-0.49221188]
11 0.0347555 [ 1.21131968] [-0.48037943]
12 0.0331046 [ 1.2062397] [-0.46883142]
13 0.0315321 [ 1.20128191] [-0.45756102]
14 0.0300343 [ 1.1964432] [-0.44656157]
15 0.0286077 [ 1.19172084] [-0.43582654]
16 0.0272487 [ 1.18711197] [-0.42534956]
17 0.0259544 [ 1.18261397] [-0.41512445]
18 0.0247216 [ 1.17822397] [-0.40514517]
19 0.0235473 [ 1.1739397] [-0.39540571]
20 0.0224288 [ 1.16975832] [-0.38590044]
21 0.0213634 [ 1.16567743] [-0.37662366]
22 0.0203486 [ 1.16169465] [-0.36756989]
23 0.019382 [ 1.15780759] [-0.35873377]
24 0.0184614 [ 1.15401399] [-0.3501

## "들여쓰기를 하셔야해여"

---
```python
print("X: 5, Y:", sess.run(hypothesis, feed_dict={X: 5}))
print("X: 2.5, Y:", sess.run(hypothesis, feed_dict={X: 2.5}))
```
### Before
```python
    print("X: 5, Y:", sess.run(hypothesis, feed_dict={X: 5}))
    print("X: 2.5, Y:", sess.run(hypothesis, feed_dict={X: 2.5}))
```
> sess.run 을 사용하려면 위에서 사용한 "with tf.Session() as sess:"  
코드보다 안쪽으로 한칸 들여쓰기가 되어있어야 해요 밑에처럼

```python
with tf.Session() as sess:
    print("X: 5, Y:", sess.run(hypothesis, feed_dict={X: 5}))
    print("X: 2.5, Y:", sess.run(hypothesis, feed_dict={X: 2.5}))
```

In [18]:
print("X: 5, Y:", sess.run(hypothesis, feed_dict={X: 5}))
print("X: 2.5, Y:", sess.run(hypothesis, feed_dict={X: 2.5}))

RuntimeError: Attempted to use a closed Session.